apiVersion: batch/v1
kind: Job
metadata:
  name: intraday-migrate
  namespace: intraday
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: alembic
          image: docker.io/rajsomesetty/intraday:v11 
          imagePullPolicy: Never
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: intraday-app-secret
                  key: DATABASE_URL
