apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: intraday-postgres
  namespace: intraday
spec:
  serviceName: intraday-postgres
  replicas: 1
  selector:
    matchLabels:
      app: intraday-postgres
  template:
    metadata:
      labels:
        app: intraday-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: intraday-postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
